# Generated by Django 5.0.2 on 2024-06-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_subject_delete_productversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
